/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2016-05-16 10:35:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class issue_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("file:/Users/nhn/.m2/repository/jstl/jstl/1.2/jstl-1.2.jar", Long.valueOf(1380624896000L));
    _jspx_dependants.put("/WEB-INF/include/head.jspf", Long.valueOf(1463321226000L));
    _jspx_dependants.put("/WEB-INF/include/tags.jspf", Long.valueOf(1463314056000L));
    _jspx_dependants.put("/WEB-INF/include/footer.jspf", Long.valueOf(1463316135000L));
    _jspx_dependants.put("/WEB-INF/include/navigation.jspf", Long.valueOf(1463394782000L));
    _jspx_dependants.put("file:/Users/nhn/.m2/repository/org/springframework/spring-webmvc/4.2.5.RELEASE/spring-webmvc-4.2.5.RELEASE.jar", Long.valueOf(1459257722000L));
    _jspx_dependants.put("jar:file:/Users/nhn/.m2/repository/jstl/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/Users/nhn/.m2/repository/jstl/jstl/1.2/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/Users/nhn/.m2/repository/org/springframework/spring-webmvc/4.2.5.RELEASE/spring-webmvc-4.2.5.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1456330292000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1.0, minimum-scale=1.0\">\n");
      out.write("<title>Issue Tracking System</title>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.4.3/dialog-polyfill.css\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://code.getmdl.io/1.1.3/material.blue_grey-orange.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/styles.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/tinymce.css\">");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"issues issues--wrap mdl-layout mdl-js-layout has-drawer is-upgraded\">\n");
      out.write("\t\t");
      out.write("\n");
      out.write("<header class=\"mdl-layout__header mdl-layout__header--waterfall\">\n");
      out.write("\t<div class=\"mdl-layout__header-row\">\n");
      out.write("\t\t<!-- Title -->\n");
      out.write("\t\t<span class=\"mdl-layout-title\">javajigi/slipp</span>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- Tabs -->\n");
      out.write("\t<div class=\"mdl-layout__tab-bar mdl-js-ripple-effect\">\n");
      out.write("\t\t<a href=\"https://github.com/javajigi/slipp\" class=\"mdl-layout__tab\">Code</a>\n");
      out.write("\t\t<a href=\"#\" class=\"mdl-layout__tab is-active\"> \n");
      out.write("\t\t\t<span class=\"mdl-badge\" data-badge=\"11\">Issues</span>\n");
      out.write("\t\t</a> \n");
      out.write("\t\t<a href=\"https://github.com/javajigi/slipp/pulls\" class=\"mdl-layout__tab\"> \n");
      out.write("\t\t\t<span class=\"mdl-badge\" data-badge=\"0\">Pull requests</span>\n");
      out.write("\t\t</a> \n");
      out.write("\t\t<a href=\"https://github.com/javajigi/slipp/wiki\" class=\"mdl-layout__tab\">Wiki</a> \n");
      out.write("\t\t<a href=\"https://github.com/javajigi/slipp/pulse\" class=\"mdl-layout__tab\">Pulse</a> \n");
      out.write("\t\t<a href=\"https://github.com/javajigi/slipp/graphs\" class=\"mdl-layout__tab\">Graphs</a>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t</div>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<div class=\"mdl-layout__drawer\">\n");
      out.write("\t<span class=\"mdl-layout-title\">GitHub</span>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\t\t<main class=\"mdl-layout__content\">\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"issues__posts mdl-grid\">\n");
      out.write("\t\t\t<div class=\"mdl-card mdl-shadow--4dp mdl-cell mdl-cell--12-col\">\n");
      out.write("\t\t\t\t<div class=\"mdl-card__menu\">\n");
      out.write("\t\t\t\t\t<button\n");
      out.write("\t\t\t\t\t\tclass=\"mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect\">\n");
      out.write("\t\t\t\t\t\t<i class=\"material-icons\">edit</i>\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t<button id=\"issues-menu-lower-right\"\n");
      out.write("\t\t\t\t\t\tclass=\"mdl-button mdl-js-button mdl-button--icon\">\n");
      out.write("\t\t\t\t\t\t<i class=\"material-icons\">more_vert</i>\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t<ul\n");
      out.write("\t\t\t\t\t\tclass=\"mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect mdl-color-text--grey-700\"\n");
      out.write("\t\t\t\t\t\tfor=\"issues-menu-lower-right\">\n");
      out.write("\t\t\t\t\t\t<li class=\"mdl-menu__item--full-bleed-divider\"><strong>Labels</strong></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"mdl-menu__item\">enhancement</li>\n");
      out.write("\t\t\t\t\t\t<li class=\"mdl-menu__item--full-bleed-divider\"><strong>Milestone</strong></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"mdl-menu__item\">No milestone</li>\n");
      out.write("\t\t\t\t\t\t<li class=\"mdl-menu__item--full-bleed-divider\"><strong>Assignee</strong></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"mdl-menu__item\">javajigi</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"mdl-card__title mdl-color-text--grey-50\">\n");
      out.write("\t\t\t\t\t<i class=\"material-icons\">check_circle</i>\n");
      out.write("\t\t\t\t\t<h2 class=\"mdl-card__title-text\">spring boot 기반 개발이 가능하도록 한다.\n");
      out.write("\t\t\t\t\t\t#227</h2>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"mdl-color-text--grey-700 mdl-card__supporting-text meta\">\n");
      out.write("\t\t\t\t\t<a href=\"https://github.com/javajigi\"> <img class=\"minilogo\"\n");
      out.write("\t\t\t\t\t\theight=\"48\" width=\"48\"\n");
      out.write("\t\t\t\t\t\tsrc=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\"\n");
      out.write("\t\t\t\t\t\talt=\"@javajigi\">\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<div class=\"author-text\">\n");
      out.write("\t\t\t\t\t\t\t<strong> <a href=\"https://github.com/javajigi\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"author\">javajigi</a>\n");
      out.write("\t\t\t\t\t\t\t</strong>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<span>11 Aug 2015</span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"section-spacer\"></div>\n");
      out.write("\t\t\t\t\t<button\n");
      out.write("\t\t\t\t\t\tclass=\"mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon\">\n");
      out.write("\t\t\t\t\t\t<i class=\"material-icons\" role=\"presentation\">thumb_up</i><span\n");
      out.write("\t\t\t\t\t\t\tclass=\"visuallyhidden\">like comment</span>\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t<button\n");
      out.write("\t\t\t\t\t\tclass=\"mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon\">\n");
      out.write("\t\t\t\t\t\t<i class=\"material-icons\" role=\"presentation\">thumb_down</i><span\n");
      out.write("\t\t\t\t\t\t\tclass=\"visuallyhidden\">dislike comment</span>\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"mdl-color-text--grey-700 mdl-card__supporting-text\">\n");
      out.write("\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t현재 모든 설정 파일도 java config 기반으로 변경했다.<br>spring boot 기반으로 설정을\n");
      out.write("\t\t\t\t\t\t변경하는 것도 가능하겠다.\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div\n");
      out.write("\t\t\t\t\tclass=\"mdl-color-text--primary-contrast mdl-card__supporting-text comments\">\n");
      out.write("\t\t\t\t\t<!-- comments start -->\n");
      out.write("\t\t\t\t\t<div class=\"comment mdl-color-text--grey-700\">\n");
      out.write("\t\t\t\t\t\t<header class=\"comment__header\"> <img\n");
      out.write("\t\t\t\t\t\t\tclass=\"comment__avatar2\" height=\"48\" width=\"48\"\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\"\n");
      out.write("\t\t\t\t\t\t\talt=\"@javajigi\">\n");
      out.write("\t\t\t\t\t\t<div class=\"comment__author\">\n");
      out.write("\t\t\t\t\t\t\t<strong> <a href=\"/javajigi\" class=\"author\">javajigi</a>\n");
      out.write("\t\t\t\t\t\t\t\t<span>added the enhancement label on 11 Aug 2015</span>\n");
      out.write("\t\t\t\t\t\t\t</strong>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\t<div class=\"comment mdl-color-text--grey-700\">\n");
      out.write("\t\t\t\t\t\t<header class=\"comment__header\"> <img\n");
      out.write("\t\t\t\t\t\t\tclass=\"comment__avatar2\" height=\"48\" width=\"48\"\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\"\n");
      out.write("\t\t\t\t\t\t\talt=\"@javajigi\">\n");
      out.write("\t\t\t\t\t\t<div class=\"comment__author\">\n");
      out.write("\t\t\t\t\t\t\t<strong> <a href=\"/javajigi\" class=\"author\">javajigi</a>\n");
      out.write("\t\t\t\t\t\t\t\t<span>self-assigned this on 11 Aug 2015</span>\n");
      out.write("\t\t\t\t\t\t\t</strong>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\t<div class=\"comment mdl-color-text--grey-700\">\n");
      out.write("\t\t\t\t\t\t<header class=\"comment__header\"> <img\n");
      out.write("\t\t\t\t\t\t\tclass=\"comment__avatar2\" height=\"48\" width=\"48\"\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\"\n");
      out.write("\t\t\t\t\t\t\talt=\"@javajigi\">\n");
      out.write("\t\t\t\t\t\t<div class=\"comment__author\">\n");
      out.write("\t\t\t\t\t\t\t<strong> <a href=\"/javajigi\" class=\"author\">javajigi</a>\n");
      out.write("\t\t\t\t\t\t\t\t<span>added this to the 반복주기 15 milestone on 11 Aug 2015</span>\n");
      out.write("\t\t\t\t\t\t\t</strong>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\t<div class=\"comment mdl-color-text--grey-700\">\n");
      out.write("\t\t\t\t\t\t<header class=\"comment__header\"> <img\n");
      out.write("\t\t\t\t\t\t\tclass=\"comment__avatar\" height=\"48\" width=\"48\"\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\"\n");
      out.write("\t\t\t\t\t\t\talt=\"@javajigi\">\n");
      out.write("\t\t\t\t\t\t<div class=\"comment__author\">\n");
      out.write("\t\t\t\t\t\t\t<strong> <a href=\"/javajigi\" class=\"author\">javajigi</a>\n");
      out.write("\t\t\t\t\t\t\t</strong> <span>11 Aug 2015</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<nav class=\"comment__actions\">\n");
      out.write("\t\t\t\t\t\t<button\n");
      out.write("\t\t\t\t\t\t\tclass=\"mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon\">\n");
      out.write("\t\t\t\t\t\t\t<i class=\"material-icons\" role=\"presentation\">thumb_up</i><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"visuallyhidden\">like comment</span>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t<button\n");
      out.write("\t\t\t\t\t\t\tclass=\"mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon\">\n");
      out.write("\t\t\t\t\t\t\t<i class=\"material-icons\" role=\"presentation\">thumb_down</i><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"visuallyhidden\">dislike comment</span>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t</nav> </header>\n");
      out.write("\t\t\t\t\t\t<div class=\"comment__text\">\n");
      out.write("\t\t\t\t\t\t\t<span>모든 소스 코드를 scala 기반으로 변경한 후에 진행하는 것이 좋을 수도 있겠다.</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\t<div class=\"comment mdl-color-text--grey-700\">\n");
      out.write("\t\t\t\t\t\t<header class=\"comment__header\"> <img\n");
      out.write("\t\t\t\t\t\t\tclass=\"comment__avatar2\" height=\"48\" width=\"48\"\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\"\n");
      out.write("\t\t\t\t\t\t\talt=\"@javajigi\">\n");
      out.write("\t\t\t\t\t\t<div class=\"comment__author\">\n");
      out.write("\t\t\t\t\t\t\t<strong> <a href=\"/javajigi\" class=\"author\">javajigi</a>\n");
      out.write("\t\t\t\t\t\t\t\t<span>removed this from the 반복주기 15 milestone on 11 Aug\n");
      out.write("\t\t\t\t\t\t\t\t\t2015</span>\n");
      out.write("\t\t\t\t\t\t\t</strong>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\t<div class=\"comment mdl-color-text--grey-700\">\n");
      out.write("\t\t\t\t\t\t<header class=\"comment__header\"> <img\n");
      out.write("\t\t\t\t\t\t\tclass=\"comment__avatar\" height=\"48\" width=\"48\"\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\"\n");
      out.write("\t\t\t\t\t\t\talt=\"@javajigi\">\n");
      out.write("\t\t\t\t\t\t<div class=\"comment__author\">\n");
      out.write("\t\t\t\t\t\t\t<strong> <a href=\"/javajigi\" class=\"author\">javajigi</a>\n");
      out.write("\t\t\t\t\t\t\t</strong> <span>17 Dec 2015</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<nav class=\"comment__actions\">\n");
      out.write("\t\t\t\t\t\t<button\n");
      out.write("\t\t\t\t\t\t\tclass=\"mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon\">\n");
      out.write("\t\t\t\t\t\t\t<i class=\"material-icons\" role=\"presentation\">thumb_up</i><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"visuallyhidden\">like comment</span>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t<button\n");
      out.write("\t\t\t\t\t\t\tclass=\"mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon\">\n");
      out.write("\t\t\t\t\t\t\t<i class=\"material-icons\" role=\"presentation\">thumb_down</i><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"visuallyhidden\">dislike comment</span>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t</nav> </header>\n");
      out.write("\t\t\t\t\t\t<div class=\"comment__text\">\n");
      out.write("\t\t\t\t\t\t\t<span>시도했으나 과정이 너무 복잡함. 이후에 다시 진행하는 것이 좋겠음.</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\t<div class=\"comment mdl-color-text--grey-700\">\n");
      out.write("\t\t\t\t\t\t<header class=\"comment__header\"> <img\n");
      out.write("\t\t\t\t\t\t\tclass=\"comment__avatar2\" height=\"48\" width=\"48\"\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://avatars2.githubusercontent.com/u/520500?v=3&amp;s=96\"\n");
      out.write("\t\t\t\t\t\t\talt=\"@javajigi\">\n");
      out.write("\t\t\t\t\t\t<div class=\"comment__author\">\n");
      out.write("\t\t\t\t\t\t\t<strong> <a href=\"/javajigi\" class=\"author\">javajigi</a>\n");
      out.write("\t\t\t\t\t\t\t\t<span>closed this on 17 Dec 2015</span>\n");
      out.write("\t\t\t\t\t\t\t</strong>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- comments end -->\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div\n");
      out.write("\t\t\t\t\tclass=\"mdl-color-text--primary-contrast mdl-card__supporting-text new-comment\">\n");
      out.write("\t\t\t\t\t<form>\n");
      out.write("\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\tclass=\"mdl-textfield mdl-js-textfield mdl-textfield--floating-label\">\n");
      out.write("\t\t\t\t\t\t\t<textarea rows=5 class=\"mdl-textfield__input\" id=\"comment\"></textarea>\n");
      out.write("\t\t\t\t\t\t\t<label for=\"comment\" class=\"mdl-textfield__label\">Leave a\n");
      out.write("\t\t\t\t\t\t\t\tcomment</label>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<button\n");
      out.write("\t\t\t\t\t\t\tclass=\"mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon\">\n");
      out.write("\t\t\t\t\t\t\t<i class=\"material-icons\" role=\"presentation\">check</i><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"visuallyhidden\">add comment</span>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t");
      out.write("<footer class=\"mdl-mini-footer\">\n");
      out.write("\t<div class=\"mdl-mini-footer--left-section\">\n");
      out.write("\t\t<div class=\"mdl-logo mdl-color-text--grey-600\">\n");
      out.write("\t\t\tProudly powered by <a href=\"https://github.com/Byeol\">Byeol</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("\t\t</footer> \n");
      out.write("\t\t</main>\n");
      out.write("\t\t<div class=\"mdl-layout__obfuscator\"></div>\n");
      out.write("\t</div>\n");
      out.write("\t<script src=\"https://code.getmdl.io/1.1.3/material.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("        ");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("        ");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /WEB-INF/include/navigation.jspf(22,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.user}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("        \t<a href=\"/users/logout\" class=\"mdl-layout__tab\" role=\"button\">Logout</a>\n");
        out.write("        \t<a href=\"/users/");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/edit\" class=\"mdl-layout__tab\" role=\"button\">Update Account</a>\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("        \t<a href=\"/users/login\" class=\"mdl-layout__tab\" role=\"button\">Login</a>\n");
        out.write("        \t<a href=\"/users/new\" class=\"mdl-layout__tab\" role=\"button\">Sign Up</a>\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }
}
